// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proj_webapi.Data;

#nullable disable

namespace proj_webapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250612004119_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proj_webapi.Models.Equipamento", b =>
                {
                    b.Property<int>("IdEquipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipamento"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEquipamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroPatrimonio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEquipamento");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("proj_webapi.Models.Sala", b =>
                {
                    b.Property<int>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSala"));

                    b.Property<int>("Andar")
                        .HasColumnType("int");

                    b.Property<string>("Metragem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdSala");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("proj_webapi.Models.SalaEquipamento", b =>
                {
                    b.Property<int>("IdSalaEquipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSalaEquipamento"));

                    b.Property<int>("IdEquipamento")
                        .HasColumnType("int");

                    b.Property<int?>("IdEquipamentoNavigationIdEquipamento")
                        .HasColumnType("int");

                    b.Property<int>("IdSala")
                        .HasColumnType("int");

                    b.Property<int?>("IdSalaNavigationIdSala")
                        .HasColumnType("int");

                    b.HasKey("IdSalaEquipamento");

                    b.HasIndex("IdEquipamentoNavigationIdEquipamento");

                    b.HasIndex("IdSalaNavigationIdSala");

                    b.ToTable("SalaEquipamentos");
                });

            modelBuilder.Entity("proj_webapi.Models.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<string>("NomeTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TipoUsuarios");
                });

            modelBuilder.Entity("proj_webapi.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoUsuarioNavigationIdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdTipoUsuarioNavigationIdTipoUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("proj_webapi.Models.Sala", b =>
                {
                    b.HasOne("proj_webapi.Models.Usuario", null)
                        .WithMany("Salas")
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("proj_webapi.Models.SalaEquipamento", b =>
                {
                    b.HasOne("proj_webapi.Models.Equipamento", "IdEquipamentoNavigation")
                        .WithMany()
                        .HasForeignKey("IdEquipamentoNavigationIdEquipamento");

                    b.HasOne("proj_webapi.Models.Sala", "IdSalaNavigation")
                        .WithMany()
                        .HasForeignKey("IdSalaNavigationIdSala");

                    b.Navigation("IdEquipamentoNavigation");

                    b.Navigation("IdSalaNavigation");
                });

            modelBuilder.Entity("proj_webapi.Models.Usuario", b =>
                {
                    b.HasOne("proj_webapi.Models.TipoUsuario", "IdTipoUsuarioNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTipoUsuarioNavigationIdTipoUsuario");

                    b.Navigation("IdTipoUsuarioNavigation");
                });

            modelBuilder.Entity("proj_webapi.Models.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("proj_webapi.Models.Usuario", b =>
                {
                    b.Navigation("Salas");
                });
#pragma warning restore 612, 618
        }
    }
}
